export const song_action_types = {
  FETCH_GENRES: 'FETCH_GENRES',
  FETCH_TRACKS: 'FETCH_TRACKS',
  SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
  FETCH_TOP_10: 'FETCH_TOP_10',
  NEXT_SONG: 'NEXT_SONG',
  PREVIOUS_SONG: 'PREVIOUS_SONG',
};

export const player_action_types = {
  PLAYER_STARTED: 'PLAYER_STARTED',
  PLAYER_PAUSED: 'PLAYER_PAUSED',
  PLAYER_STOPPED: 'PLAYER_STOPPED',
  REPEAT_CURRENT: 'REPEAT_CURRENT',
  REPEAT_NO_MUSIC: 'REPEAT_NO_MUSIC',
};
